# typed: false
# frozen_string_literal: true

# This file was generated by Herald's release workflow. DO NOT EDIT.
class Herald < Formula
  desc "Terminal email client and inbox cleanup tool"
  homepage "https://github.com/herald-email/herald-mail-app"
  license "FSL-1.1-ALv2"

  on_macos do
    on_arm do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.7.0-beta.1/herald-v0.7.0-beta.1-darwin-arm64.tar.gz"
      sha256 "8e10ad9871ec1063751542ac8c6849d695dd573fd054d278dd1516a4374f858b"
    end

    on_intel do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.7.0-beta.1/herald-v0.7.0-beta.1-darwin-amd64.tar.gz"
      sha256 "f7edc128e492c2c04b3c1ce07cb1045f818f777cb8d03e4e4d9d93b45691df7f"
    end
  end

  def install
    bin.install "herald"
    bin.install "herald-mcp-server"
    bin.install "herald-ssh-server"
  end

  test do
    system bin/"herald", "--version"
    system bin/"herald", "mcp", "--version"
    system bin/"herald", "ssh", "--version"
    system bin/"herald-mcp-server", "--version"
    system bin/"herald-ssh-server", "--version"

    request = '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
    assert_match "\"tools\"", shell_output("echo '#{request}' | #{bin}/herald mcp --demo")
  end
end
