# typed: false
# frozen_string_literal: true

# This file was generated by Herald's release workflow. DO NOT EDIT.
class Herald < Formula
  desc "Terminal email client and inbox cleanup tool"
  homepage "https://github.com/herald-email/herald-mail-app"
  license "FSL-1.1-ALv2"

  on_macos do
    on_arm do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.6.2-beta.1/herald-v0.6.2-beta.1-darwin-arm64.tar.gz"
      sha256 "7c40cff5db9eaaf40c9870816d1ef86b6add29cec7cb13c8c76492c4ad543975"
    end

    on_intel do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.6.2-beta.1/herald-v0.6.2-beta.1-darwin-amd64.tar.gz"
      sha256 "cb4bf35c2c5e4c6a8163bfe1e1a631cb1be0363fd8b08f32534ad3d69597f270"
    end
  end

  def install
    bin.install "herald"
    bin.install "herald-mcp-server"
    bin.install "herald-ssh-server"
  end

  test do
    system bin/"herald", "--version"
    system bin/"herald", "mcp", "--version"
    system bin/"herald", "ssh", "--version"
    system bin/"herald-mcp-server", "--version"
    system bin/"herald-ssh-server", "--version"

    request = '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
    assert_match "\"tools\"", shell_output("echo '#{request}' | #{bin}/herald mcp --demo")
  end
end
