# typed: false
# frozen_string_literal: true

# This file was generated by Herald's release workflow. DO NOT EDIT.
class Herald < Formula
  desc "Terminal email client and inbox cleanup tool"
  homepage "https://github.com/herald-email/herald-mail-app"
  license "FSL-1.1-ALv2"

  on_macos do
    on_arm do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.1.6-beta.1/herald-v0.1.6-beta.1-darwin-arm64.tar.gz"
      sha256 "e2c7af06515fb23bd0e461b535fd6d57655998ea72eec8a83519679df2c8118b"
    end

    on_intel do
      url "https://github.com/herald-email/herald-mail-app/releases/download/v0.1.6-beta.1/herald-v0.1.6-beta.1-darwin-amd64.tar.gz"
      sha256 "59e956c32ae8f1d5a4f10d7ae5099e99a22cce888cfe773541818aa177f9d1c0"
    end
  end

  def install
    bin.install "herald"
    bin.install "herald-mcp-server"
    bin.install "herald-ssh-server"
  end

  test do
    system bin/"herald", "--version"
    system bin/"herald", "mcp", "--version"
    system bin/"herald", "ssh", "--version"
    system bin/"herald-mcp-server", "--version"
    system bin/"herald-ssh-server", "--version"

    request = '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
    assert_match "\"tools\"", shell_output("echo '#{request}' | #{bin}/herald mcp --demo")
  end
end
